global using System.Collections.Immutable;
global using System.Windows.Input;
global using Microsoft.Extensions.DependencyInjection;
global using Windows.Networking.Connectivity;
global using Windows.Storage;
global using Microsoft.Extensions.Hosting;
global using Microsoft.Extensions.Logging;
global using Microsoft.UI.Xaml;
global using Microsoft.UI.Xaml.Automation;
global using Microsoft.UI.Xaml.Controls;
global using Microsoft.UI.Xaml.Controls.Primitives;
global using Microsoft.UI.Xaml.Data;
global using Microsoft.UI.Xaml.Media;
global using Microsoft.UI.Xaml.Navigation;
global using Microsoft.Extensions.Options;
global using RMUtility.Business.Models;
global using RMUtility.Infrastructure;
global using RMUtility.Presentation;
global using RMUtility.DataContracts;
global using RMUtility.DataContracts.Serialization;
global using RMUtility.Services.Caching;
global using RMUtility.Services.Endpoints;
global using Uno.UI;
global using Uno.Extensions.Markup;
global using Uno.Themes.Markup;
global using Windows.ApplicationModel;
global using ApplicationExecutionState = Windows.ApplicationModel.Activation.ApplicationExecutionState;
global using Color = Windows.UI.Color;
